<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>injectionSelector</key>
    <string>L:text.html.markdown</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#fenced-codeblock-verilog</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>fenced-codeblock-verilog</key>
      <dict>
        <key>begin</key>
        <string>(?:^|\G)(\s*)(`{3,}|~{3,})\s*(?i:(v|verilog)(?:\s+[^`~]*)?$)</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.markdown</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>fenced_code.block.language</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>fenced_code.block.language.attributes</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?:^|\G)(\1|\s{0,3})(\2)\s*$</string>
        <key>endCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.markdown</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(^|\G)\s*.*</string>
            <key>while</key>
            <string>(^|\G)(?!\s*[`~]{3,}\s*$)</string>
            <key>contentName</key>
            <string>meta.embedded.block.verilog</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.verilog</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>markdown.verilog.codeblock</string>
  </dict>
</plist>